# Generated by Django 5.2a1 on 2025-03-11 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0001_initial'),
        ('fees', '0004_remove_chargeschedule_charge_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargetype',
            name='bkge_class_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_types_bkge_filter', to='fees.bkgeclass'),
        ),
        migrations.AlterField(
            model_name='chargetype',
            name='producer_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees.producer'),
        ),
    ]
