# Generated by Django 5.2a1 on 2025-03-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0002_alter_chargetype_bkge_class_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
