# Generated by Django 5.2a1 on 2025-03-18 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0003_alter_chargeschedule_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='charge_type',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='total_gst',
        ),
        migrations.AddField(
            model_name='charge',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='charges.chargeschedule'),
        ),
    ]
