# Generated by Django 5.2a1 on 2025-04-10 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_commissionperiod'),
        ('charges', '0004_remove_charge_charge_type_remove_charge_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='commission_period',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='accounting.commissionperiod'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='charges.chargeschedule'),
        ),
    ]
