# Generated by Django 5.2a1 on 2025-07-10 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0005_charge_commission_period_alter_charge_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='original_charge',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='charges.charge'),
        ),
    ]
