# Generated by Django 5.2a1 on 2025-02-13 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(max_length=5, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('abn', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=50)),
                ('address_2', models.CharField(max_length=50)),
                ('address_3', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('suburb', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=5)),
                ('payment_account_name', models.CharField(max_length=50)),
                ('payment_account_bsb', models.CharField(max_length=6)),
                ('payment_account_number', models.CharField(max_length=16)),
                ('is_gst_exempt', models.BooleanField(default=False)),
                ('is_external', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BkgeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='fees.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=50)),
                ('cash_amount', models.FloatField()),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=1)),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.producer')),
            ],
        ),
        migrations.CreateModel(
            name='JournalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('external_adviser', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('gst', models.FloatField()),
                ('details', models.CharField(max_length=100)),
                ('lender_amount', models.FloatField()),
                ('lender_gst', models.FloatField()),
                ('balance', models.FloatField()),
                ('limit', models.FloatField()),
                ('bkge_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.bkgeclass')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='fees.journal')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('gst', models.FloatField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.agent')),
                ('journal_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.journaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='DealSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.agent')),
                ('bkge_class_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees.bkgeclass')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='fees.deal')),
                ('producer_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees.producer')),
            ],
        ),
        migrations.CreateModel(
            name='ProducerClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='fees.deal')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.producer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client_code', 'producer')},
            },
        ),
        migrations.AddField(
            model_name='journaldetail',
            name='client_account_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_details', to='fees.producerclient'),
        ),
    ]
