# Generated by Django 5.2a1 on 2025-02-15 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='created_by',
        ),
    ]
