# Generated by Django 5.2a1 on 2025-03-03 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_remove_journal_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('bkge_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_types', to='fees.bkgeclass')),
                ('bkge_class_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_types_bkge_filter', to='fees.bkgeclass')),
                ('producer_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.producer')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=10)),
                ('allow_partial_payment', models.BooleanField()),
                ('roll_balance', models.BooleanField()),
                ('status', models.CharField(max_length=10)),
                ('priority', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.FloatField()),
                ('gst', models.FloatField()),
                ('paying_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paying_schedules', to='fees.agent')),
                ('receiving_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_schedules', to='fees.agent')),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='fees.chargetype')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('total_gst', models.FloatField()),
                ('outstanding_amount', models.FloatField()),
                ('outstanding_gst', models.FloatField()),
                ('status', models.CharField(max_length=10)),
                ('priority', models.IntegerField(default=0)),
                ('original_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.charge')),
                ('paying_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paying_charges', to='fees.agent')),
                ('receiving_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_charges', to='fees.agent')),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='fees.chargetype')),
            ],
        ),
    ]
