# Generated by Django 5.2a1 on 2025-03-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_chargetype_chargeschedule_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargeschedule',
            name='charge_type',
        ),
        migrations.RemoveField(
            model_name='chargeschedule',
            name='paying_agent',
        ),
        migrations.RemoveField(
            model_name='chargeschedule',
            name='receiving_agent',
        ),
        migrations.RemoveField(
            model_name='chargetype',
            name='bkge_class',
        ),
        migrations.RemoveField(
            model_name='chargetype',
            name='bkge_class_filter',
        ),
        migrations.RemoveField(
            model_name='chargetype',
            name='producer_filter',
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
        migrations.DeleteModel(
            name='ChargeSchedule',
        ),
        migrations.DeleteModel(
            name='ChargeType',
        ),
    ]
