# Generated by Django 5.2a1 on 2025-03-11 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0002_alter_chargetype_bkge_class_filter_and_more'),
        ('fees', '0004_remove_chargeschedule_charge_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaldetail',
            name='related_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_journal_details', to='charges.charge'),
        ),
    ]
