# Generated by Django 5.2a1 on 2025-04-10 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_commissionperiod'),
        ('fees', '0005_journaldetail_related_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='commission_period',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='accounting.commissionperiod'),
        ),
    ]
