# Generated by Django 5.2a1 on 2025-04-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_journal_commission_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='address_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='address_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='payment_account_bsb',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='payment_account_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='payment_account_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
