# Generated by Django 5.2a1 on 2025-05-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_alter_agent_address_2_alter_agent_address_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaldetail',
            name='external_adviser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journaldetail',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
