# Generated by Django 5.2a1 on 2025-05-17 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_alter_journaldetail_external_adviser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journaldetail',
            old_name='client_account_code',
            new_name='client_account',
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('external_adviser', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField()),
                ('gst', models.FloatField()),
                ('details', models.CharField(max_length=100)),
                ('lender_amount', models.FloatField()),
                ('lender_gst', models.FloatField()),
                ('balance', models.FloatField()),
                ('limit', models.FloatField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='fees.agent')),
                ('bkge_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.bkgeclass')),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.producerclient')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.journaldetail')),
            ],
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
