# Generated by Django 5.2a1 on 2025-05-17 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0005_charge_commission_period_alter_charge_schedule'),
        ('fees', '0009_rename_client_account_code_journaldetail_client_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='related_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charges.charge'),
        ),
    ]
