# Generated by Django 5.2a1 on 2025-07-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_fee_related_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='bkge_class',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='client_account',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='details',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='external_adviser',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='lender_amount',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='lender_gst',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='product',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='related_charge',
        ),
    ]
