# Generated by Django 5.2a1 on 2025-07-05 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_rename_client_account_journaldetail_client_account_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journaldetail',
            old_name='client_account_code',
            new_name='client_account',
        ),
    ]
